name: YSDSOFT-CI-Check # İşlemin adı

on:
  push:
    branches: [ "main" ] # Sadece main dalına kod gönderince çalışır
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest # Testler Linux (Ubuntu) üzerinde yapılacak

    steps:
    - uses: actions/checkout@v4 # Kodlarını GitHub sunucusuna çeker

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:

        php-version: '8.4'

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create .env for Testing
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute Tests
      run: php artisan test # Projedeki testleri çalıştırır
